apiVersion: v1
kind: Secret
metadata:
    name: grafana-basic-auth-credentials
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:0uRLBVcxN+YqREX56X5gNIQJhIj8i7jaSzMu733uCqbkUkC8qZl/esAq6iKZjpIltvcpM14baB2XiXhIdIXOBYSBnQ==,iv:vMUC9tp3rYS2vrpob31Gjf2mh6iUCdDAaZmHhIqIsPk=,tag:7gmS95NRxEEqLC5IH+6kmg==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RkVSK3dVdVBVSDBoQjVx
            R1p0eTdjUGZ6a1B1V1YzSm5xL2w1ZkNidmc4CmtJZEloT1drZFIwSFpUMDBBdkhV
            bTE1dVltbXlScVlpclExVUJ2d2xDY0UKLS0tIE8wWjJ0YjFXemJacVM3ZlVlNXAv
            aDRNT0xYRkF0dHNhYkNCNUVHMnhnVGMKSJ8Gl5ia4d3YcVLmukS3uZJExMb302Ef
            V1xAYB6QZcDKphogD+AAF8WK3stHxMP1SYRqszLV3vN9iKGH0x0QKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T06:32:26Z"
    mac: ENC[AES256_GCM,data:8PyY+vTNY6/2CTr01LHSMJD/cngl8UGzop8wAVvyKJcmfA+nKKbwxFXJpAtWTobt67n+7JXW1aghJNcBsXMal+W5X9Dx/pRMGcmETu2J6FIn++AKBXT+9sTWXwv2vpkBGv2YGwxPZ5OQdvVJz0TFIgi0AiM8sSM4e+IJgHGo4Mg=,iv:CvsC4gt2+krN93zyCwGlJozErZDWnBN1XrLQF/ObW3k=,tag:920VsKH/MsGuhXIa2fQD1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
