apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:Vz2Ciek=,iv:2BdueAo/zrDWwM2PSkaatQGpzXQSj5AE8MNM0XXlvNg=,tag:p4Jns39Ulob6ZmAx3fLnVw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:paaXj4tp6RZqno5F5Zq6WNe+,iv:YXKlwkfoyFjvOEbOf4zqayT1gQPNQc5HztrFTRZjPg0=,tag:+M8pKTQQvaTa+Yp6atm/Yg==,type:str]
    users: ENC[AES256_GCM,data:PcF+LoQSVHlu0lI1fLXFdKAIVmATgUUqqAacPMM/unLXoFzEsKXf9RMYkMLFDXBRd8GqZft88zadwyu9BBgmw3bhtA==,iv:SaIaRqfNfrC9rSzPsEmUC4or9QZ7fwS3LyFRK/i4AGI=,tag:2k9RikSf9boyaPtjcyOcfg==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSm9PMU1Rc2hLanhyOHZR
            QlRYNFdHbHhxYyt4eXFhRU9qOHJKTWpaVWpBCkl6YVlyTDUrSkhjS0pWbkU3enU1
            RlFyVE5tZmRlOXBEa0dCa1JIejdCejgKLS0tIHBudlBXVEQrY1ZHVDZwYWdzQXor
            blVYR2o4U0o0RmtwTnQrS3JWTWI5VUEKYGjFoIa42YO8zlo/u32/kGz94oyBn22r
            ORQtqTQWnQQzdOaCJ9OQGDnU2eb1+twRXTB+pkP98Tah9tTbb45A+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T06:02:13Z"
    mac: ENC[AES256_GCM,data:V5LUEIRZwaDeZxnZ+ajQ8ojyPWQDTNMNZ4QpHNDJ/UdZc2xzcCQhEZE6SzKM93dMRqjvH03a3st/65qgdJfKKPJ5UELEa8rq0J5QSRXJFI/HfuHO7EpTKpwob97oqVSDll5y9uSW0ZE/lmWpOY+JX5dJpuHfDtyFvGAzltjMR/Y=,iv:vqcXs5/RLEADeCu5yFYPb945uG6ZugFVDS4bDRJK2tA=,tag:MsUwYdaWqBctGgnMyoS7gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
