apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:Vz2Ciek=,iv:2BdueAo/zrDWwM2PSkaatQGpzXQSj5AE8MNM0XXlvNg=,tag:p4Jns39Ulob6ZmAx3fLnVw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ChzaxkGxONoOJ6MizP28KimRxvgw+22/MNh57Vd5Ff4=,iv:K8AMQu+RPiP0/pSGIWlXox5enmnECrfR7gZ7rkXFOTI=,tag:H45aZc1XvloAmPnlG/5V9w==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSm9PMU1Rc2hLanhyOHZR
            QlRYNFdHbHhxYyt4eXFhRU9qOHJKTWpaVWpBCkl6YVlyTDUrSkhjS0pWbkU3enU1
            RlFyVE5tZmRlOXBEa0dCa1JIejdCejgKLS0tIHBudlBXVEQrY1ZHVDZwYWdzQXor
            blVYR2o4U0o0RmtwTnQrS3JWTWI5VUEKYGjFoIa42YO8zlo/u32/kGz94oyBn22r
            ORQtqTQWnQQzdOaCJ9OQGDnU2eb1+twRXTB+pkP98Tah9tTbb45A+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T20:20:25Z"
    mac: ENC[AES256_GCM,data:QdsYnTc8IaYS0s6JsqTT9g1w4wsZmZEZPH4Bs64MEs/PSKXXw3tzUiafUggAgL1jyx/aymyZYUb+Hrjqd/GVn+um27zaKSApWuNQo3P+1ZaiNuJLbQgaPOGWHygv1tymP6ewp084Y8UO60ZwVoMyl+sdUfR8x/Iv4tSSfGjDfs0=,iv:8iquJJdCx6NDgtKZqIqXh1QJJ/3ICPSUcTXGypKiVeQ=,tag:WBqZAbP4kjVkYHaWTplMvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
