apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:TEpRxg==,iv:/QI/I9/RTZi6at1QwcWMGpb+/7ZSHJYEFJxZKjezcfg=,tag:mF9En29jHAviF3hTL2SA4A==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:iAoTWA==,iv:4Hw2Vdh0TRL6XHPer3gLl1o3glv5ckCHtqV937XFg80=,tag:Zo2VDhnOZ17WJSawgXKh8Q==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSm9PMU1Rc2hLanhyOHZR
            QlRYNFdHbHhxYyt4eXFhRU9qOHJKTWpaVWpBCkl6YVlyTDUrSkhjS0pWbkU3enU1
            RlFyVE5tZmRlOXBEa0dCa1JIejdCejgKLS0tIHBudlBXVEQrY1ZHVDZwYWdzQXor
            blVYR2o4U0o0RmtwTnQrS3JWTWI5VUEKYGjFoIa42YO8zlo/u32/kGz94oyBn22r
            ORQtqTQWnQQzdOaCJ9OQGDnU2eb1+twRXTB+pkP98Tah9tTbb45A+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T14:25:59Z"
    mac: ENC[AES256_GCM,data:d/JIo99FWkUNP5o3LJAIkBSpLatnFNAhcJcF+gVMadQGoizoMbbIfMOAHHlr45imKHU247di1G3h9+VTiMNXVGpxfipTp6MDf7gIzGmt0T5n9EVD+R0MmE3bW8pU4q5N/vFwojg7FVWIDmZhIcfkZYf9IJffFdTQcZwXhyZ4qYI=,iv:v9auzIi0ffLSSKIXDMpCQjry3+a/j/McjgtDBaArI3Q=,tag:rfASmPX8ijKqlLBu5JZgZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
